trigger: none
pr: none

parameters:
#Beta Parms
  - name: ServiceConnection
    type: string
    default: PipelineServicesBeta-dev

  - name: TFStorageAccount
    type: string
    default: terraformbackendaf731d5f

resources:
  repositories:
    - repository: AzureTerraformState
      type: git
      name: CPT/AzureTerraformState
      ref:  beta

stages:
  - stage: KRS_Deploy_MI
    displayName: KRS Deploy Managed Identity
  
    variables:
    - group: krs-beta
  
    jobs:
    - template: continuous-deployment-terraform.yml@AzureTerraformState
      parameters:
        serviceConnection:           ${{ parameters.ServiceConnection }}

        TfVars:
          TF_AZ_REGION_NAME:         $(AZ_REGION_NAME)
          TF_AZ_RESOURCE_GROUP_NAME: $(AZ_RESOURCE_GROUP_NAME)
          TF_AZ_LOG_SUBSCRIPTION_ID: $(AZ_LOG_SUBSCRIPTION_ID)

        #Environment settings
        environment:                 beta
        displayName:                 cd-krs-managed-identity
        jobName:                     cd_krs_managed_identity

        #Terraform settings
        backendFileName:             krs-beta-mi.tfstate
        directoryToExecute:          src/ServicePrincipalRotation/devops/terraform/managed-identity
        storageAccountName:          ${{ parameters.TFStorageAccount }}

        #Service Now Configuration
        applicationDeploymentName:   KRS-Beta-MI
        applicationServiceName:      Azure - Cloud Platforms-Sandbox
  
        #Azure settings
        appResourceGroupName:        default-easus-rg # use this param when testing custom resource group
        deployRegion:                eastus #use this param when using multi-region