trigger: none
pr: none

resources:
   repositories:
      - repository: Catalog
        type:       git
        name:       ALM/OfficialDevOpsPipelineTemplateCatalog


stages:
   - template: /Stages/DotNetCoreBuild/V1.yml@Catalog
     parameters:
        displayName: CI_KRS_Single_Rotation
        dotNetVersion:      6
        enableartifactoryupload: false
        BuildConfiguration: Release
        userBuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'      
        ProjectPaths:       src/ServicePrincipalRotation/ServicePrincipalRotation.csproj