trigger: none
pr: none

parameters:
  - name: ServiceConnection
    type: string
    default: PipelineServicesBeta-dev

  - name: TFStorageAccount
    type: string
    default: terraformbackendaf731d5f

  - name: AppServicePlanName
    type: string
    default: linux-p1v2-ap

  - name: ManagedIdentity
    type: string
    default: krs-adraeg-mi

  - name: PipelineLibName
    type: string
    default: KRS-Beta

resources:
  repositories:
   - repository: AzureTerraformState
     type:       git
     name:       CPT/AzureTerraformState
     ref:        beta
  pipelines:
    - pipeline:    CIPipeline
      source:      ci-krs-function-app

variables:
  - group: ${{ parameters.PipelineLibName }}

stages:
   - template: /Stages/TerraformDestroy/V1.yml@AzureTerraformState
     parameters:
       TfVars:
         TF_AZ_APP_INSIGHTS_LOG_ANALYTICS_NAME:  $(AZ_APP_INSIGHTS_LOG_ANALYTICS_NAME)
         TF_AZ_APP_SERVICE_PLAN_NAME:            ${{ parameters.AppServicePlanName }}
         TF_AZ_FUNC_NAME:                        $(KRS_BETA_FUNC_APP_NAME)
         TF_AZ_LOG_SUBSCRIPTION_ID:              $(AZ_LOG_SUBSCRIPTION_ID)
         TF_AZ_REGION_NAME:                      $(AZ_REGION_NAME)
         TF_AZ_RESOURCE_GROUP_NAME:              $(AZ_RESOURCE_GROUP_NAME)
         TF_AZ_SUB_PROVISION_TAG:                $(AZ_SUB_PROVISION_TAG)
         TF_AZ_SUBNET_NAME:                      $(AZ_SUBNET_NAME)
         TF_AZ_TENANT_ID:                        $(AZ_TENANT_ID)
         TF_REQ_STORAGE_ACCOUNT:                 $(REQ_STORAGE_ACCOUNT)

         #KRS
         TF_AZURECREATION_KV_NAME:               $(AZURECREATION_KV_NAME)
         TF_DEVOPS_API_URL:                      $(DEVOPS_API_URL)
         TF_DEVOPS_PAT_KV_SECRET_NAME:           $(DEVOPS_PAT_KV_SECRET_NAME)
         TF_IS_TEST:                             $(IS_TEST)
         TF_KRS_AUTO_TAKE:                       $(KRS_AUTO_TAKE)
         TF_KRS_AUTO_BATCH:                      $(KRS_AUTO_BATCH)
         TF_MANAGED_IDENTITY_CLIENT_ID:          $(MANAGED_IDENTITY_CLIENT_ID)
         TF_MANAGED_IDENTITY_NAME:               ${{ parameters.ManagedIdentity }}
         TF_SECRET_EXP_OFFSET:                   $(SECRET_EXP_OFFSET)
         TF_SNOWFLAKE_KV_NAME:                   $(SNOWFLAKE_KV_NAME)
         TF_SRV_PRINC_CLIENT_ID:                 $(SRV_PRINC_CLIENT_ID)
         TF_SRV_PRINC_KV_SECRET_NAME:            $(SRV_PRINC_KV_SECRET_NAME)
         TF_KRS_APPROVED_TAG:                    $(KRS_APPROVED_TAG)
         
       environment:                terraformDestroy
       DisplayName:                funcapp default destroy
       JobName:                    FuncAppDefaultDestroy

       serviceConnection:          ${{ parameters.ServiceConnection }}
 
       DirectoryToExecute:         $(KRS_DIRECTORY_TO_EXECUTE)
       storageAccountName:         ${{ parameters.TFStorageAccount }}
       resourceGroupName:          terraform-rg
       containerName:              terraformcontainer
       backendFileName:            $(TFStateFileName)

       applicationServiceName:     Azure - Cloud Platforms-Sandbox
       applicationDeploymentName:  KRS-Beta-Destroy